### ISSUE TITLE
Create a Home View in the Users app

### ISSUE THREAD

**Issue by svp19** [oss2019/crispy-ai#12]
We need to create a homepage for users who login. For now, having a simple html page with a heading `Hello Users!` will suffice. Do ensure to put this html template in the path specified below. Also do create a home view (function-based) to render this html template.

**Tasks**
- [ ] Define a home view in users/views.py
- [ ] Create a `users/templates/users/home.html` (You might have to create this folder)
- [ ] Render home.html in the home view in users/views.py

Note: Do not add the required urls, this will be taken up as a separate issue.

**Comment by svp19** [comment]
Please leave a comment if you would like to take this issue
