### ISSUE TITLE
Create a View to Register Users

### ISSUE THREAD

**Issue by svp19** [oss2019/crispy-ai#15]
Since, we will be making a login authentication system, we need a view to register users to the `users app`. 

**Tasks**
- [ ] Use the built-in `UsersCreationForm` to register users in Register View in `users/views.py`
- [ ] create a register.html template in  `users/templates/users/` folder.
- [ ] render the form - created in the register view - in this html template
- [ ] add the url path 'register/' for this view in users/views.py

**Comment by ayush1999guptA** [comment]
i will do it

**Comment by svp19** [comment]
Sure @ayush1999guptA , I will assign this issue to you as soon as you accept the invitation through email.
