### ISSUE TITLE
Login/Logout Authentication

### ISSUE THREAD

**Issue by svp19** [oss2019/crispy-ai#16]
Users need to be able to login to gain access to crispy-powered courses ;)
Here we add simple login/logout functionality using Django's built in features. 

**Tasks**
- [ ] Use Django auth_views to add a Login/Logout view in `crispy_ai/urls.py`
- [ ] Create the templates `users/login.html` and `users/logout.html`
- [ ] Add a LOGIN_REDIRECT_URL to the Home View in settings.py
- [ ] In `users/logout.html` add a link to login again

**Comment by vedangj044** [comment]
May i work on this issue ?

**Comment by vedangj044** [comment]
please review pull request

**Comment by svp19** [comment]
@vedangj044 I've sent you an invitation in email, I will assign this issue to you after you accept it :)
